// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jun2020_webapi.Models;

namespace jun2020_webapi.Migrations
{
    [DbContext(typeof(MecContext))]
    [Migration("20200825104915_prva")]
    partial class prva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("jun2020_webapi.Models.Igrac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Atprang")
                        .HasColumnType("int");

                    b.Property<int>("Godine")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MecId")
                        .HasColumnType("int");

                    b.Property<int>("Poeni")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MecId");

                    b.ToTable("Igraci");
                });

            modelBuilder.Entity("jun2020_webapi.Models.Mec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Listapoena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vreme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mecevi");
                });

            modelBuilder.Entity("jun2020_webapi.Models.Igrac", b =>
                {
                    b.HasOne("jun2020_webapi.Models.Mec", "Mec")
                        .WithMany("Igraci")
                        .HasForeignKey("MecId");
                });
#pragma warning restore 612, 618
        }
    }
}
