// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using januar2020grupaA.Models;

namespace januar2020grupaA.Migrations
{
    [DbContext(typeof(FabrikaContext))]
    partial class FabrikaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("januar2020grupaA.Models.Fabrika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fabrike");
                });

            modelBuilder.Entity("januar2020grupaA.Models.Silos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FabrikaId")
                        .HasColumnType("int");

                    b.Property<int>("Kapaciteti")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FabrikaId");

                    b.ToTable("Silosi");
                });

            modelBuilder.Entity("januar2020grupaA.Models.Silos", b =>
                {
                    b.HasOne("januar2020grupaA.Models.Fabrika", "Fabrika")
                        .WithMany("Silosi")
                        .HasForeignKey("FabrikaId");
                });
#pragma warning restore 612, 618
        }
    }
}
