// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using januar2020grupaB.Models;

namespace januar2020grupaB.Migrations
{
    [DbContext(typeof(BibliotekaContext))]
    [Migration("20200315170701_prva")]
    partial class prva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("januar2020grupaB.Models.Biblioteka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Biblioteke");
                });

            modelBuilder.Entity("januar2020grupaB.Models.Polica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BibliotekaId")
                        .HasColumnType("int");

                    b.Property<int>("MaksBroj")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrenutniBroj")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BibliotekaId");

                    b.ToTable("Police");
                });

            modelBuilder.Entity("januar2020grupaB.Models.Polica", b =>
                {
                    b.HasOne("januar2020grupaB.Models.Biblioteka", "Biblioteka")
                        .WithMany("Police")
                        .HasForeignKey("BibliotekaId");
                });
#pragma warning restore 612, 618
        }
    }
}
